apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekaserver
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      containers:
        - name: eurekaserver
          image: mallikarredla7674/eureka-server:latest
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_APPLICATION_NAME
              value: "eurekaserver"
            - name: EUREKA_SERVER
              value: "eureka-service"
            - name: SPRING_PROFILES_ACTIVE
              value: "cloud"
            - name: SERVER_PORT
              value: "8761"
            - name: ZIPKIN_SERVER
              value: "zipkin-service"
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
spec:
  selector:
    app: eurekaserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
