apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-mysql-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-database-deployment
spec:
  selector:
    matchLabels:
      app: user-database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user-database
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: userdb
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: user-mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: user-database-service
spec:
  type: ClusterIP
  selector:
    app: user-database
  ports:
    - port: 3306
      targetPort: 3306
